package com.example.parkingmanager.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.Date;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ParkingmanagerTransactionCollection")
public class Transaction {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "transactionId")
    private String transactionId;
    @DynamoDBAttribute(attributeName = "beginDate")
    private Date beginDate;
    @DynamoDBAttribute(attributeName = "plate")
    private String plate;
    @DynamoDBAttribute(attributeName = "finishDate")
    private Date finishDate;
    @DynamoDBAttribute(attributeName = "vehicleType")
    private Integer vehicleType;
    @DynamoDBAttribute(attributeName = "status")
    private Integer status;
    @DynamoDBAttribute(attributeName = "stayedTime")
    private Long stayedTime;

    public Transaction(String plate, Long stayedTime) {
        this.plate = plate;
        this.stayedTime = stayedTime;
    }

    public Transaction(String plate, Integer vehicleType, Long stayedTime) {
        this.plate = plate;
        this.vehicleType = vehicleType;
        this.stayedTime = stayedTime;
    }

}
