package com.example.parkingmanager.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.Date;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@DynamoDBTable(tableName = "AverageParkingCollection")
public class AverageParking {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "averageId")
    private String averageId;
    @DynamoDBAttribute(attributeName = "vehicleType")
    private String vehicleType;
    @DynamoDBAttribute(attributeName = "avgStayedTime")
    private Double avgStayedTime;

}
