package com.example.parkingmanager.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@DynamoDBTable(tableName = "LongestStayParkingCollection")
public class LongestStayParking {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "transactionId")
    private String transactionId;

    @DynamoDBAttribute(attributeName = "plate")
    private String plate;

    @DynamoDBAttribute(attributeName = "avgStayedTime")
    private Double avgStayedTime;



}
